services:
  svfe-api-firmador:
    image: svfe/svfe-api-firmador:v20230109
    container_name: svfe-api-firmador
    ports:
      - "8113:8113"
    volumes:
      - ./temp:/uploads
    restart: unless-stopped
